name: language
on:
  pull_request:
    branches:
      - master
jobs:
  linter_name:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-languagetool@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: info
          language: 'it'
          patterns: '**/*.rst'
          disabled_categories: ''
